// @Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// @Register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// @Authorization
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// @Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// @Profile
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

// @UploadModal
export const SHOW_UPLOAD_MODAL = 'SHOW_UPLOAD_MODAL';

// @Performance Upload
export const PERFORMANCE_UPLOAD_SUCCESS = 'PERFORMANCE_UPLOAD_SUCCESS';
export const PERFORMANCE_UPLOAD_FAIL = 'PERFORMANCE_UPLOAD_FAIL';

// @Set Performance
export const SHOW_UPLOADED_PERFORMANCE = 'SHOW_UPLOADED_PERFORMANCE';
export const SEARCH_PERFORMANCE_BY_DAY = 'SHOW_PERFORMANCE_BY_DAY';
export const SEARCH_PERFORMANCE_BY_WEEK = 'SHOW_PERFORMANCE_BY_WEEK';
export const SEARCH_PERFORMANCE_BY_MONTH = 'SHOW_PERFORMANCE_BY_MONTH';
export const SEARCH_QUARTERLY_PERFORMANCE = 'SEARCH_QUARTERLY_PERFORMANCE';
export const SEARCH_PERFORMANCE = 'SEARCH_PERFORMANCE';
